/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scene.gltf -o app/components/models/DaliWindow.tsx --transform 
Files: public/models/scene.gltf [16.99KB] > C:\Users\KIIT0001\Desktop\p\app\components\models\scene-transformed.glb [1.08MB] (-6270%)
Author: betocarrillo (https://sketchfab.com/betocarrillo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/woman-at-the-window-by-dali-11039ba1a12b40cbb7c3b3a355f49501
Title: Woman at the window by Dali
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
  }
  materials: {
    brush_ThickPaint: THREE.MeshBasicMaterial
    brush_Ink: THREE.MeshBasicMaterial
    brush_UnlitHull: THREE.MeshBasicMaterial
    brush_Marker: THREE.MeshBasicMaterial
    brush_OilPaint: THREE.MeshBasicMaterial
    media_image_AS02157: THREE.MeshBasicMaterial
  }
 // animations: GLTFAction[]
}

export function Memory(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/scene-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.brush_ThickPaint} scale={0.941} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.brush_Ink} scale={0.941} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.brush_UnlitHull} scale={0.941} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.brush_Marker} scale={0.941} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.brush_OilPaint} scale={0.941} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.media_image_AS02157} position={[0.164, 1.259, 2.634]} rotation={[0.005, -0.027, -0.002]} scale={27.445} />
    </group>
  )
}

useGLTF.preload('/models/scene-transformed.glb')
