/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/projects.glb --output app/components/models/Perro.tsx 
Author: betocarrillo (https://sketchfab.com/betocarrillo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/perro-semihundido-7a63b7e21a934cefb89f1a6a4048105e
Title: Perro Semihundido
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    brush_UnlitHull: THREE.MeshBasicMaterial
    brush_ThickPaint: THREE.MeshBasicMaterial
    media_image_57264_1: THREE.MeshBasicMaterial
  }
  animations: any[]
}

export function Perro(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/projects.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.56}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.brush_UnlitHull} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.brush_ThickPaint} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.media_image_57264_1} position={[-0.336, 1.612, -2.175]} rotation={[3.056, 0.169, 3.114]} scale={20.607} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/projects.glb')
